### ISSUE TITLE
solution branch has no solutions

### ISSUE THREAD

**Issue by erankova** [learn-co-curriculum/dsc-filtering-lab-v2-4#1]
## Issue Subtype

- [ ] Master branch code
- [x] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [x] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by erankova** [comment]
solution branch has no solutions

**Comment by bpurdy-ds** [comment]
Thank you for bringing to to our attention. We'll take a look.

**Comment by bpurdy-ds** [comment]
Just cloned the solution branch and it ran as it is supposed to. As such, I don't see an issue. If you still there is one, then please reopen it.
